//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part3HelloWindowsClient.Part3HelloService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeType", Namespace="http://schemas.datacontract.org/2004/07/Part10Employee")]
    public enum EmployeeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartTime = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Part3HelloService.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployee", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeResponse")]
        Part3HelloWindowsClient.Part3HelloService.EmployeeInfo GetEmployee(Part3HelloWindowsClient.Part3HelloService.EmployeeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployee", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeResponse")]
        System.Threading.Tasks.Task<Part3HelloWindowsClient.Part3HelloService.EmployeeInfo> GetEmployeeAsync(Part3HelloWindowsClient.Part3HelloService.EmployeeRequest request);
        
        // CODEGEN: Generating message contract since the operation SaveEmployee is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/SaveEmployee", ReplyAction="http://tempuri.org/IEmployeeService/SaveEmployeeResponse")]
        Part3HelloWindowsClient.Part3HelloService.SaveEmployeeResponse SaveEmployee(Part3HelloWindowsClient.Part3HelloService.EmployeeInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/SaveEmployee", ReplyAction="http://tempuri.org/IEmployeeService/SaveEmployeeResponse")]
        System.Threading.Tasks.Task<Part3HelloWindowsClient.Part3HelloService.SaveEmployeeResponse> SaveEmployeeAsync(Part3HelloWindowsClient.Part3HelloService.EmployeeInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeRequestObject", WrapperNamespace="http://DNS.com/Employee", IsWrapped=true)]
    public partial class EmployeeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://DNS.com/Employee")]
        public string LicenseKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DNS.com/Employee", Order=0)]
        public int EmployeeId;
        
        public EmployeeRequest() {
        }
        
        public EmployeeRequest(string LicenseKey, int EmployeeId) {
            this.LicenseKey = LicenseKey;
            this.EmployeeId = EmployeeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeInfoObject", WrapperNamespace="http://DNS.com/Employee", IsWrapped=true)]
    public partial class EmployeeInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DNS.com/Employee", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DNS.com/Employee", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DNS.com/Employee", Order=2)]
        public string Gender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DNS.com/Employee", Order=3)]
        public System.DateTime DateOfBirth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DNS.com/Employee", Order=4)]
        public Part3HelloWindowsClient.Part3HelloService.EmployeeType Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DNS.com/Employee", Order=5)]
        public double AnnualSalary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DNS.com/Employee", Order=6)]
        public double HourlySalary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DNS.com/Employee", Order=7)]
        public double HourlyWorked;
        
        public EmployeeInfo() {
        }
        
        public EmployeeInfo(int Id, string Name, string Gender, System.DateTime DateOfBirth, Part3HelloWindowsClient.Part3HelloService.EmployeeType Type, double AnnualSalary, double HourlySalary, double HourlyWorked) {
            this.Id = Id;
            this.Name = Name;
            this.Gender = Gender;
            this.DateOfBirth = DateOfBirth;
            this.Type = Type;
            this.AnnualSalary = AnnualSalary;
            this.HourlySalary = HourlySalary;
            this.HourlyWorked = HourlyWorked;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveEmployeeResponse {
        
        public SaveEmployeeResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : Part3HelloWindowsClient.Part3HelloService.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<Part3HelloWindowsClient.Part3HelloService.IEmployeeService>, Part3HelloWindowsClient.Part3HelloService.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Part3HelloWindowsClient.Part3HelloService.EmployeeInfo Part3HelloWindowsClient.Part3HelloService.IEmployeeService.GetEmployee(Part3HelloWindowsClient.Part3HelloService.EmployeeRequest request) {
            return base.Channel.GetEmployee(request);
        }
        
        public int GetEmployee(string LicenseKey, int EmployeeId, out string Name, out string Gender, out System.DateTime DateOfBirth, out Part3HelloWindowsClient.Part3HelloService.EmployeeType Type, out double AnnualSalary, out double HourlySalary, out double HourlyWorked) {
            Part3HelloWindowsClient.Part3HelloService.EmployeeRequest inValue = new Part3HelloWindowsClient.Part3HelloService.EmployeeRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.EmployeeId = EmployeeId;
            Part3HelloWindowsClient.Part3HelloService.EmployeeInfo retVal = ((Part3HelloWindowsClient.Part3HelloService.IEmployeeService)(this)).GetEmployee(inValue);
            Name = retVal.Name;
            Gender = retVal.Gender;
            DateOfBirth = retVal.DateOfBirth;
            Type = retVal.Type;
            AnnualSalary = retVal.AnnualSalary;
            HourlySalary = retVal.HourlySalary;
            HourlyWorked = retVal.HourlyWorked;
            return retVal.Id;
        }
        
        public System.Threading.Tasks.Task<Part3HelloWindowsClient.Part3HelloService.EmployeeInfo> GetEmployeeAsync(Part3HelloWindowsClient.Part3HelloService.EmployeeRequest request) {
            return base.Channel.GetEmployeeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Part3HelloWindowsClient.Part3HelloService.SaveEmployeeResponse Part3HelloWindowsClient.Part3HelloService.IEmployeeService.SaveEmployee(Part3HelloWindowsClient.Part3HelloService.EmployeeInfo request) {
            return base.Channel.SaveEmployee(request);
        }
        
        public void SaveEmployee(int Id, string Name, string Gender, System.DateTime DateOfBirth, Part3HelloWindowsClient.Part3HelloService.EmployeeType Type, double AnnualSalary, double HourlySalary, double HourlyWorked) {
            Part3HelloWindowsClient.Part3HelloService.EmployeeInfo inValue = new Part3HelloWindowsClient.Part3HelloService.EmployeeInfo();
            inValue.Id = Id;
            inValue.Name = Name;
            inValue.Gender = Gender;
            inValue.DateOfBirth = DateOfBirth;
            inValue.Type = Type;
            inValue.AnnualSalary = AnnualSalary;
            inValue.HourlySalary = HourlySalary;
            inValue.HourlyWorked = HourlyWorked;
            Part3HelloWindowsClient.Part3HelloService.SaveEmployeeResponse retVal = ((Part3HelloWindowsClient.Part3HelloService.IEmployeeService)(this)).SaveEmployee(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Part3HelloWindowsClient.Part3HelloService.SaveEmployeeResponse> Part3HelloWindowsClient.Part3HelloService.IEmployeeService.SaveEmployeeAsync(Part3HelloWindowsClient.Part3HelloService.EmployeeInfo request) {
            return base.Channel.SaveEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Part3HelloWindowsClient.Part3HelloService.SaveEmployeeResponse> SaveEmployeeAsync(int Id, string Name, string Gender, System.DateTime DateOfBirth, Part3HelloWindowsClient.Part3HelloService.EmployeeType Type, double AnnualSalary, double HourlySalary, double HourlyWorked) {
            Part3HelloWindowsClient.Part3HelloService.EmployeeInfo inValue = new Part3HelloWindowsClient.Part3HelloService.EmployeeInfo();
            inValue.Id = Id;
            inValue.Name = Name;
            inValue.Gender = Gender;
            inValue.DateOfBirth = DateOfBirth;
            inValue.Type = Type;
            inValue.AnnualSalary = AnnualSalary;
            inValue.HourlySalary = HourlySalary;
            inValue.HourlyWorked = HourlyWorked;
            return ((Part3HelloWindowsClient.Part3HelloService.IEmployeeService)(this)).SaveEmployeeAsync(inValue);
        }
    }
}
